// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
/// // ...
// await Firebase.initializeApp(
//  options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKxQarIq7A01BQzbU1Z3NtLApXFNedSXc',
    appId: '1:277065975026:web:10977878d00fefd3e57c6b',
    messagingSenderId: '277065975026',
    projectId: 'cleaning-app-eb668',
    authDomain: 'cleaning-app-eb668.firebaseapp.com',
    storageBucket: 'cleaning-app-eb668.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3KJpjOC7Gw17KES7St96dWmQrfzO2BZQ',
    appId: '1:277065975026:android:374c8d9c40125b75e57c6b',
    messagingSenderId: '277065975026',
    projectId: 'cleaning-app-eb668',
    storageBucket: 'cleaning-app-eb668.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOVWNwafLX6EcOvf30WEtaPsRA6QVUA5s',
    appId: '1:277065975026:ios:4ca59bd831bc9993e57c6b',
    messagingSenderId: '277065975026',
    projectId: 'cleaning-app-eb668',
    storageBucket: 'cleaning-app-eb668.firebasestorage.app',
    iosBundleId: 'com.example.cleaningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOVWNwafLX6EcOvf30WEtaPsRA6QVUA5s',
    appId: '1:277065975026:ios:4ca59bd831bc9993e57c6b',
    messagingSenderId: '277065975026',
    projectId: 'cleaning-app-eb668',
    storageBucket: 'cleaning-app-eb668.firebasestorage.app',
    iosBundleId: 'com.example.cleaningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKxQarIq7A01BQzbU1Z3NtLApXFNedSXc',
    appId: '1:277065975026:web:d3ab182ae06f5624e57c6b',
    messagingSenderId: '277065975026',
    projectId: 'cleaning-app-eb668',
    authDomain: 'cleaning-app-eb668.firebaseapp.com',
    storageBucket: 'cleaning-app-eb668.firebasestorage.app',
  );
}
